package ninja.unagi.scan

data class ObservationInput(
  val name: String?,
  val address: String?,
  val rssi: Int,
  val timestamp: Long,
  val serviceUuids: List<String>,
  val manufacturerData: Map<Int, String>,
  val serviceData: Map<String, String> = emptyMap(),
  val source: String,
  val transport: String? = null,
  val advertisedName: String? = null,
  val systemName: String? = null,
  val nameSource: String? = null,
  val vendorName: String? = null,
  val vendorSource: String? = null,
  val vendorConfidence: String? = null,
  val locallyAdministeredAddress: Boolean? = null,
  val normalizedAddress: String? = null,
  val addressType: String? = null,
  val addressTypeLabel: String? = null,
  val rawAndroidAddressType: Int? = null,
  val deviceType: Int? = null,
  val deviceTypeLabel: String? = null,
  val bondState: Int? = null,
  val bondStateLabel: String? = null,
  val advertiseFlags: Int? = null,
  val txPowerLevel: Int? = null,
  val resultTxPower: Int? = null,
  val connectable: Boolean? = null,
  val legacy: Boolean? = null,
  val dataStatus: Int? = null,
  val primaryPhy: Int? = null,
  val secondaryPhy: Int? = null,
  val advertisingSid: Int? = null,
  val periodicAdvertisingInterval: Int? = null,
  val appearance: Int? = null,
  val appearanceLabel: String? = null,
  val classicMajorClass: Int? = null,
  val classicMajorClassLabel: String? = null,
  val classicDeviceClass: Int? = null,
  val classicDeviceClassLabel: String? = null,
  val classificationFingerprint: String? = null,
  val classificationCategory: String? = null,
  val classificationLabel: String? = null,
  val classificationConfidence: String? = null,
  val classificationEvidence: List<String> = emptyList()
)
